// ============================================================
// src/i18n.js - Idiomas y traducción
// ============================================================

import { CFG } from './config.js';

export const TEXT = {
  es: {
    loadBtn: "Cargar MIDI",
    onboardingTitle1: '¡Bienvenido a MidiMate!',
    onboardingBody1: 'Toca el piano con tu mouse, tu teclado de PC o un teclado MIDI físico. Vamos a mostrarte lo básico en unos segundos.',
    onboardingTitle2: 'Carga una canción',
    onboardingBody2: 'Usa el botón "Cargar MIDI" (arriba a la izquierda) o simplemente arrastra un archivo .mid a la ventana. Puedes tener varias canciones en tu lista de reproducción.',
    onboardingTitle3: 'Elige cómo practicar',
    onboardingBody3: '"Libre" para tocar sin guía · "Ver" para observar cómo se toca la canción · "Practicar" para que la app espere a que aciertes cada nota, con marcador de precisión en vivo.',
    onboardingTitle4: 'Personalízalo todo',
    onboardingBody4: 'El ícono ⚙ (abajo a la derecha) abre los ajustes: temas de color, efectos visuales, instrumentos por pista, atajos de teclado y mucho más. ¡A tocar!',
    onboardingNext: 'Siguiente',
    onboardingStart: 'Empezar ▶',
    playlistEmpty: 'Vacía',
    play: "▶ Reproducir",
    pause: "⏸ Pausar",
    practice: "▶ Practicar",
    noMidiDevice: "Sin dispositivo MIDI",
    speed: "Velocidad",
    sectionMode: "Modo de uso",
    loadMidiLabel: "Archivo",
    groupGeneral: "General y modo",
    groupBackground: "Fondo",
    groupAppearance: "Apariencia (colores, skins, teclado)",
    groupButtons: "Asignación de botones (editar atajos y teclado)",
    groupAudio: "Audio (sintetizador, EQ, instrumentos)",
    groupPlaylist: "Lista de reproducción",
    sectionPlaylist: "Lista de reproducción",
    playlistReorderHint: "Arrastra las pistas o usa los botones ▲/▼ para cambiar el orden de reproducción.",
    catAesthetic: "Estético",
    catButtons: "Asignación de botones",
    catAudio: "Audio",
    freeDisplayLabel: "Modo Libre: mostrar como",
    freeDisplayText: "Texto grande",
    freeDisplayStaff: "Partitura real",
    mutedToast: "Silenciado (M para restaurar)",
    unmutedToast: "Volumen restaurado",
    volumeWarning: "Volumen por encima de 250% — riesgo de distorsión/daño auditivo",
    sectionGeneral: "General",
    drawerLayoutLabel: "Diseño de la pantalla de ajustes",
    layoutFullscreen: "Pantalla completa",
    layoutDynamic: "Pantalla completa dinámica",
    layoutSidebar: "Panel lateral",
    language: "Idioma",
    toastDuration: "Duración del aviso (segundos)",
    sectionAnnounce: "Aviso central",
    announceEnable: "Mostrar aviso al cargar un MIDI",
    announceTextLabel: "Texto (vacío = nombre del archivo)",
    announceFontLabel: "Fuente",
    fontDisplay: "Elegante (serif)",
    fontBody: "Moderna (sans-serif)",
    announceSizeLabel: "Tamaño",
    announceColorLabel: "Color del texto",
    sectionFlags: "Funciones",
    sectionCtrlVis: "Controles visibles (barra superior)",
    mouseHideDelayLabel: "Segundos antes de ocultar el mouse",
    sectionBackground: "Fondo",
    baseColor: "Color base",
    bgImageLabel: "Imagen de fondo (archivo local)",
    bgLayersHint: "Hasta 3 capas simultáneas (imagen, GIF o video). Los archivos más cortos que la canción se repiten en bucle. Puedes moverlas libremente, sin que tengan que encajar en las esquinas.",
    bgLayerTitle: "Capa",
    bgLayerEmpty: "vacía",
    bgLayerHasImage: "imagen",
    bgLayerHasVideo: "video",
    bgLayerOrderLabel: "Posición (orden)",
    bgOrderBack: "Fondo",
    bgOrderMiddle: "Medio",
    bgOrderFront: "Frente",
    bgZoomLabel: "Zoom de la imagen",
    bgPanXLabel: "Posición horizontal",
    bgPanYLabel: "Posición vertical",
    harmonizeBtn: "Combinar colores con la imagen",
    harmonizeDone: "Colores combinados con la imagen",
    sectionSkins: "Estilos (skins)",
    keySkinLabel: "Diseño de las teclas",
    tileSkinLabel: "Diseño de los tides",
    sectionKeyCount: "Teclado visible",
    keyCountLabel: "Cantidad de teclas en pantalla",
    keyCountOpt2: "Compacto",
    keyCountOpt3: "Amplio",
    keyCountOpt4: "Todas las teclas (88)",
    keyCountOpt5: "Automático (según el MIDI)",
    modeHint: "Elige el modo arriba (pestañas). Libre = tocas en vivo; Ver = miras la canción; Practicar = estudias con feedback.",
    reportBtn: "Generar reporte de funciones (TXT)",
    reportDesc: "Descarga un archivo con el listado de todas las funciones de la app, además de los errores registrados en esta sesión.",
    factoryResetBtn: "Restablecer todo",
    factoryResetDesc: "Borra toda la configuración guardada (temas, atajos, playlist, ajustes) y recarga la página con los valores de fábrica.",
    exportHint: "Elige el formato, presiona ⏺ en la barra superior (o la tecla R), y luego Play para reproducir la canción. Al presionar ⏺ de nuevo (o Stop), el video se descarga solo — compatible con YouTube, Instagram, TikTok y X.",
    recordFormatLabel: "Formato / red social",
    fxExplosion: "Explosión",
    fxWave: "Onda",
    fxRain: "Lluvia de estrellas",
    skinTracks: "Color por pista",
    skinClassic: "Clásico",
    skinFlat: "Plano",
    skinNeon: "Neón",
    skinGlow: "Resplandor",
    skinOutline: "Contorno",
    skinHarmonize: "Armonizado con la imagen",
    skinChroma: "Color por nota (chroma)",
    keyFxStyleLabel: "Efecto al tocar",
    fxFlash: "Destello",
    fxSparks: "Chispas",
    fxSmoke: "Humo",
    fxFire: "Fuego",
    fxBubbles: "Burbujas",
    fxLightning: "Relámpago",
    settingsBgColorLabel: "Color de fondo de esta pantalla de ajustes",
    panelColorLabel: "Color secundario (paneles/tarjetas)",
    staffNoteColorLabel: "Color de las notas en la partitura",
    staffBgColorLabel: "Color de fondo de la partitura",
    sectionCountIn: "Cuenta regresiva",
    countInEnable: "Activar cuenta regresiva antes de reproducir",
    countInAudio: "Sonido durante la cuenta regresiva",
    removeImage: "Quitar imagen",
    imageOpacity: "Opacidad de la imagen",
    sectionSynth: "Sintetizador",
    analyzeMidiBtn: "Analizar MIDI y optimizar sonido",
    realisticAudioLabel: "Sonido realista (muestras reales, requiere internet)",
    realisticAudioDesc: "Aplica a todos los instrumentos del sintetizador (piano, cuerdas, vientos, metales, percusión, etc). Pesa más y tarda un instante en cargar cada nota la primera vez.",
    analyzeMidiHint: "Ajusta automáticamente instrumento y ecualizador según la canción cargada.",
    autoOptimized: "Sonido optimizado según el MIDI cargado",
    noMidiToAnalyze: "Carga un MIDI primero.",
    bassAmountLabel: "Cuerpo / graves del piano",
    soundSource: "Fuente de sonido",
    soundSourceAllApplied: "Instrumento aplicado a todas las pistas (solo esta canción)",
    keepAllPreset: "Mantener instrumento en todas las pistas",
    on: "ACTIVADO",
    off: "DESACTIVADO",
    synthPiano: "Piano sintetizado",
    synthGrand: "Piano de cola",
    synthUpright: "Piano vertical",
    synthHarpsichord: "Clavecín",
    synthEpiano: "Piano eléctrico",
    synthOrgan: "Órgano",
    groupPiano: "Piano",
    groupStrings: "Cuerdas",
    groupPercussion: "Percusión",
    groupWinds: "Vientos",
    groupBrass: "Metales",
    groupOther: "Otros",
    synthViolin: "Violín",
    synthGuitarClassical: "Guitarra española",
    synthGuitarAcoustic: "Guitarra acústica",
    synthGuitarElectric: "Guitarra eléctrica",
    synthMusicBox: "Caja musical",
    synthPerc1: "Percusión 1 (caja)",
    synthPerc2: "Percusión 2 (tambor)",
    synthPerc3: "Percusión 3 (platillo)",
    synthFlute: "Flauta",
    synthSax: "Saxofón",
    synthOcarina: "Ocarina",
    synthBrass1: "Metales 1 (trompeta)",
    synthBrass2: "Metales 2 (trombón)",
    synthBrass3: "Metales 3 (corno)",
    synthTuba: "Tuba",
    synthViola: "Viola",
    synthCello: "Cello",
    synthContrabass: "Contrabajo",
    synthClarinet: "Clarinete",
    synthOboe: "Oboe",
    synthBassoon: "Fagot",
    synthTimpani: "Tímpani",
    synthPad: "Pad suave",
    synthBell: "Campana",
    synthSample: "Muestra local (archivo de audio)",
    sampleFileLabel: "Archivo de muestra (una nota grabada)",
    sampleNoteLabel: "Nota de la muestra (afinación base)",
    sectionMetronome: "Metrónomo",
    metronomeEnable: "Activar metrónomo",
    metronomeBpm: "Tempo del metrónomo (BPM)",
    sectionKeymap: "Teclado de PC",
    addNoteMapLabel: "Agregar una nota nueva al mapeo",
    addNoteMapBtn: "Agregar",
    sectionShortcuts: "Atajos de teclado",
    sectionEQ: "Ecualizador",
    eqLow: "Graves",
    eqMid: "Medios",
    eqHigh: "Agudos",
    dropNotMidi: "Ese archivo no es un MIDI (.mid/.midi)",
    eqPresetLabel: "Preset",
    eqFlat: "Plano",
    eqRock: "Rock",
    eqClassical: "Clásica",
    eqJazz: "Jazz",
    eqPop: "Pop",
    eqElectronic: "Electrónica",
    eqVocal: "Realce de piano",
    pressKeyToast: "Presiona la tecla física que quieras asignar…",
    shortcutPlayPause: "Reproducir/Pausar",
    shortcutMute: "Silenciar",
    shortcutSeekBack: "Retroceder 5s",
    shortcutSeekFwd: "Adelantar 5s",
    shortcutFullscreen: "Pantalla completa",
    shortcutSustain: "Activar/desactivar pedal de sostener",
    shortcutOpenFile: "Abrir archivo MIDI",
    shortcutVolUp: "Subir volumen",
    shortcutVolDown: "Bajar volumen",
    shortcutObsClean: "Activar/desactivar modo limpio (OBS)",
    shortcutPlaylistPrev: "Pista anterior",
    shortcutPlaylistNext: "Pista siguiente",
    shortcutStop: "Detener",
    shortcutLoopToggle: "Activar/desactivar loop",
    shortcutPlaylistToggle: "Abrir/cerrar playlist",
    shortcutRecordToggle: "Grabar/detener video",
    groupExport: "Exportar video",
    sectionExport: "Grabar y exportar video",
    keymapHint: 'Haz clic en "Reasignar", luego presiona la tecla física que quieras usar para esa nota.',
    remap: "Reasignar",
    resetDefault: "Restablecer por defecto",
    ctrlLoad: "Botón Cargar MIDI",
    ctrlPlay: "Botón Reproducir",
    ctrlMidiIn: "Selector de dispositivo MIDI",
    ctrlTempo: "Control de velocidad",
    flagFallingNotes: "Notas cayendo",
    flagFallingNotesDesc: "Ribbons que caen hacia la tecla.",
    flagSheet: "Partitura superior",
    flagSheetDesc: "Pentagrama sincronizado con posición diatónica.",
    flagFollow: "Modo seguimiento",
    flagFollowDesc: "Espera a que toques la nota correcta.",
    flagAccuracy: "Marcador de precisión",
    flagAccuracyDesc: "Muestra % de aciertos en vivo.",
    flagObs: "Modo limpio (OBS)",
    flagObsDesc: "Oculta toda la interfaz salvo el ícono ⚙.",
    hintLoadFile: "Carga un archivo MIDI para empezar",
    errorReadingMidi: "Error leyendo el MIDI: ",
    webMidiUnavailable: "Web MIDI no disponible — usa clic o el teclado de tu PC.",
    webMidiDenied: "Se denegó el acceso MIDI. Revisa los permisos del navegador.",
    accuracyLabel: "Precisión",
    sampleLoaded: "Muestra de audio cargada: ",
    sampleDecodeError: "No se pudo decodificar el archivo de audio.",
    ctrlTransport: "Botones de retroceder/detener/adelantar",
    ctrlVolume: "Control de volumen",
    ctrlFullscreen: "Botón de pantalla completa",
    ctrlLoop: "Botón de repetir (loop)",
    flagNoteNames: "Nombres de nota en las teclas",
    flagNoteNamesDesc: "Muestra el nombre sobre cada tecla del piano.",
    flagProgress: "Barra de progreso",
    flagProgressDesc: "Muestra el avance y tiempo restante de la canción.",
    flagAutoHide: "Ocultar el mouse al tocar",
    flagAutoHideDesc: "Oculta el cursor tras unos segundos sin moverlo.",
    flagVirtualClick: "Clic en teclado virtual",
    flagVirtualClickDesc: "Permite tocar notas haciendo clic en el piano.",
    flagSustain: "Sostener notas (pedal)",
    flagSustainDesc: "Mantiene sonando la nota tras soltar la tecla, como el pedal de sustain.",
    flagTouchMode: "Modo táctil",
    flagTouchModeDesc: "Optimiza el teclado para pantallas táctiles (detectado automáticamente).",
    chordLabel: "Acorde",
    noChord: "",
    sectionNoteNaming: "Sistema de nombres de nota",
    noteNamingEn: "Inglés (C D E)",
    noteNamingLatin: "Latino (Do Re Mi)",
    noteNamingDe: "Alemán (C D E, H)",
    sectionVolume: "Volumen",
    fullscreenOn: "Pantalla completa",
    shortcutsHint: "Atajos: Espacio reproducir/pausar · ← / → retroceder/adelantar 5s · M silenciar · Shift mantener pedal de sostener",
    flagLoop: "Repetir canción (loop)",
    flagLoopDesc: "Al terminar, vuelve a empezar automáticamente.",
    flagBeatLines: "Líneas de compás",
    flagBeatLinesDesc: "Marca cada tiempo/pulso en la zona de notas cayendo.",
    flagKeyFx: "Efectos visuales al tocar",
    flagKeyFxDesc: "Destello que se expande al presionar una tecla.",
    sectionColorTheme: "Tema de color",
    themeBrass: "Latón (por defecto)",
    themeOcean: "Océano",
    themeRose: "Rosa",
    themeEmerald: "Esmeralda",
    themeMono: "Monocromo",
    themeCustom: "Personalizado (imagen)",
    sectionInstruments: "Instrumentos por pista",
    instrumentsHint: "Aparece al cargar un MIDI. \"Auto-reproducir\" hace que esa pista suene sola durante la reproducción, con el instrumento elegido — en Practicar tú decides qué pista suena sola y cuál tocas tú; en Ver todas suenan solas siempre.",
    trackLabel: "Pista",
    trackNoNotes: "sin notas",
    trackMute: "Silenciar",
    trackAuto: "Auto-reproducir",
    trackVisible: "Mostrar en partitura/notas",
    trackDisable: "Desactivar pista",
    noTracksYet: "Carga un MIDI para ver sus pistas.",
    watchModeAutoNote: "En modo Ver todas las pistas se auto-reproducen siempre — este interruptor solo aplica en modo Practicar.",
    modeFree: "Libre",
    modeWatch: "Ver",
    modePractice: "Practicar",
    freeModeLabel: "Modo libre",
    modePromptTitle: "¿Cómo quieres usar este MIDI?",
    sectionEffects: "Efectos globales",
    humanizeLabel: "Humanizar",
    swingLabel: "Swing",
    flagNoteNamesTiles: "Nombres de nota en los tiles",
    flagNoteNamesTilesDesc: "Muestra el nombre de la nota sobre cada tile (nota cayendo).",
    flagPerspective3D: "Perspectiva 3D",
    flagPerspective3DDesc: "Profundidad visual en las notas que caen (sin WebGL).",
    flagBpmPulse: "Pulso visual BPM",
    flagBpmPulseDesc: "Resalta el beat actual con pulso luminoso.",
    flagDynamicCamera: "Cámara dinámica",
    flagDynamicCameraDesc: "Zoom y paneo automático según densidad de notas.",
    flagShowChordNames: "Mostrar nombres de acorde",
    flagShowChordNamesDesc: "Muestra el acorde formado por las notas tocadas.",
    sectionLevels: "Nivel de dificultad",
    levelBeginner: "Principiante",
    levelIntermediate: "Intermedio",
    levelAdvanced: "Avanzado",
    levelHint: "Ajusta rango de teclas, velocidad y lookahead según el nivel.",
    perspectiveDepthLabel: "Profundidad 3D",
    pulseIntensityLabel: "Intensidad del pulso",
    cameraSmoothingLabel: "Suavizado de cámara"
  },
  en: {
    loadBtn: "Load MIDI",
    onboardingTitle1: "Welcome to MidiMate!",
    onboardingBody1: "Play the piano with your mouse, your PC keyboard, or a physical MIDI keyboard. We will show you the basics in a few seconds.",
    onboardingTitle2: "Load a song",
    onboardingBody2: "Use the \"Load MIDI\" button (top-left) or just drag a .mid file into the window. You can keep several songs in your playlist.",
    onboardingTitle3: "Choose how to practice",
    onboardingBody3: "\"Free\" to play without guidance · \"View\" to watch how the song is played · \"Practice\" to have the app wait until you hit each note, with a live accuracy marker.",
    onboardingTitle4: "Customize everything",
    onboardingBody4: "The ⚙ icon (bottom-right) opens settings: color themes, visual effects, per-track instruments, keyboard shortcuts, and much more. Let us play!",
    onboardingNext: "Next",
    onboardingStart: "Start ▶",
    playlistEmpty: "Empty",
    play: "▶ Play",
    pause: "⏸ Pause",
    practice: "▶ Practice",
    noMidiDevice: "No MIDI device",
    speed: "Speed",
    sectionMode: "Usage mode",
    loadMidiLabel: "File",
    groupGeneral: "General & mode",
    groupBackground: "Background",
    groupAppearance: "Appearance (colors, skins, keyboard)",
    groupButtons: "Button assignment (edit shortcuts & keymap)",
    groupAudio: "Audio (synth, EQ, instruments)",
    groupPlaylist: "Playlist",
    sectionPlaylist: "Playlist",
    playlistReorderHint: "Drag tracks or use ▲/▼ buttons to change playback order.",
    catAesthetic: "Aesthetic",
    catButtons: "Button assignment",
    catAudio: "Audio",
    freeDisplayLabel: "Free mode: display as",
    freeDisplayText: "Big text",
    freeDisplayStaff: "Real staff",
    mutedToast: "Muted (press M to restore)",
    unmutedToast: "Volume restored",
    volumeWarning: "Volume above 250% — risk of distortion/hearing damage",
    sectionGeneral: "General",
    drawerLayoutLabel: "Settings screen layout",
    layoutFullscreen: "Full screen",
    layoutDynamic: "Dynamic full screen",
    layoutSidebar: "Side panel",
    language: "Language",
    toastDuration: "Notice duration (seconds)",
    sectionAnnounce: "Center announcement",
    announceEnable: "Show announcement when loading a MIDI",
    announceTextLabel: "Text (empty = file name)",
    announceFontLabel: "Font",
    fontDisplay: "Elegant (serif)",
    fontBody: "Modern (sans-serif)",
    announceSizeLabel: "Size",
    announceColorLabel: "Text color",
    sectionFlags: "Features",
    sectionCtrlVis: "Visible controls (top bar)",
    mouseHideDelayLabel: "Seconds before hiding the mouse",
    sectionBackground: "Background",
    baseColor: "Base color",
    bgImageLabel: "Background image (local file)",
    bgLayersHint: "Up to 3 simultaneous layers (image, GIF, or video). Files shorter than the song loop automatically. You can move them freely, without needing to fit any corner.",
    bgLayerTitle: "Layer",
    bgLayerEmpty: "empty",
    bgLayerHasImage: "image",
    bgLayerHasVideo: "video",
    bgLayerOrderLabel: "Position (stacking order)",
    bgOrderBack: "Back",
    bgOrderMiddle: "Middle",
    bgOrderFront: "Front",
    bgZoomLabel: "Image zoom",
    bgPanXLabel: "Horizontal position",
    bgPanYLabel: "Vertical position",
    harmonizeBtn: "Match colors to image",
    harmonizeDone: "Colors matched to image",
    sectionSkins: "Skins",
    keySkinLabel: "Key design",
    tileSkinLabel: "Tile design",
    sectionKeyCount: "Visible keyboard",
    keyCountLabel: "Number of keys on screen",
    keyCountOpt2: "Compact",
    keyCountOpt3: "Wide",
    keyCountOpt4: "All keys (88)",
    keyCountOpt5: "Automatic (based on MIDI)",
    modeHint: "Pick the mode above (tabs). Free = you play live; Watch = watch the song; Practice = study with feedback.",
    reportBtn: "Generate functions report (TXT)",
    reportDesc: "Downloads a file listing every app function plus the errors logged this session.",
    factoryResetBtn: "Reset everything",
    factoryResetDesc: "Erases all saved settings (themes, shortcuts, playlist, options) and reloads the page with factory defaults.",
    exportHint: "Choose a format, press ⏺ on the top bar (or key R), then Play to play the song. Pressing ⏺ again (or Stop) downloads the video automatically — compatible with YouTube, Instagram, TikTok and X.",
    recordFormatLabel: "Format / social network",
    fxExplosion: "Explosion",
    fxWave: "Wave",
    fxRain: "Star rain",
    skinTracks: "Color by track",
    skinClassic: "Classic",
    skinFlat: "Flat",
    skinNeon: "Neon",
    skinGlow: "Glow",
    skinOutline: "Outline",
    skinHarmonize: "Matched to image",
    skinChroma: "Note color (chroma)",
    keyFxStyleLabel: "Key-press effect",
    fxFlash: "Flash",
    fxSparks: "Sparks",
    fxSmoke: "Smoke",
    fxFire: "Fire",
    fxBubbles: "Bubbles",
    fxLightning: "Lightning",
    settingsBgColorLabel: "Background color of this settings screen",
    panelColorLabel: "Secondary color (panels/cards)",
    staffNoteColorLabel: "Staff note color",
    staffBgColorLabel: "Staff background color",
    sectionCountIn: "Count-in",
    countInEnable: "Enable count-in before playing",
    countInAudio: "Sound during count-in",
    removeImage: "Remove image",
    imageOpacity: "Image opacity",
    sectionSynth: "Synthesizer",
    analyzeMidiBtn: "Analyze MIDI and optimize sound",
    realisticAudioLabel: "Realistic sound (real samples, requires internet)",
    realisticAudioDesc: "Applies to all synthesizer instruments (piano, strings, winds, brass, percussion, etc). Heavier, and each note takes a moment to load the first time.",
    analyzeMidiHint: "Automatically adjusts instrument and equalizer based on the loaded song.",
    autoOptimized: "Sound optimized based on the loaded MIDI",
    noMidiToAnalyze: "Load a MIDI file first.",
    bassAmountLabel: "Piano body / bass",
    soundSource: "Sound source",
    soundSourceAllApplied: "Instrument applied to all tracks (this song only)",
    keepAllPreset: "Keep instrument on all tracks",
    on: "ON",
    off: "OFF",
    synthPiano: "Synth piano",
    synthGrand: "Grand piano",
    synthUpright: "Upright piano",
    synthHarpsichord: "Harpsichord",
    synthEpiano: "Electric piano",
    synthOrgan: "Organ",
    groupPiano: "Piano",
    groupStrings: "Strings",
    groupPercussion: "Percussion",
    groupWinds: "Winds",
    groupBrass: "Brass",
    groupOther: "Other",
    synthViolin: "Violin",
    synthGuitarClassical: "Spanish guitar",
    synthGuitarAcoustic: "Acoustic guitar",
    synthGuitarElectric: "Electric guitar",
    synthMusicBox: "Music box",
    synthPerc1: "Percussion 1 (snare)",
    synthPerc2: "Percussion 2 (tom)",
    synthPerc3: "Percussion 3 (cymbal)",
    synthFlute: "Flute",
    synthSax: "Saxophone",
    synthOcarina: "Ocarina",
    synthBrass1: "Brass 1 (trumpet)",
    synthBrass2: "Brass 2 (trombone)",
    synthBrass3: "Brass 3 (horn)",
    synthTuba: "Tuba",
    synthViola: "Viola",
    synthCello: "Cello",
    synthContrabass: "Contrabass",
    synthClarinet: "Clarinet",
    synthOboe: "Oboe",
    synthBassoon: "Bassoon",
    synthTimpani: "Timpani",
    synthPad: "Soft pad",
    synthBell: "Bell",
    synthSample: "Local sample (audio file)",
    sampleFileLabel: "Sample file (one recorded note)",
    sampleNoteLabel: "Sample note (base pitch)",
    sectionMetronome: "Metronome",
    metronomeEnable: "Enable metronome",
    metronomeBpm: "Metronome tempo (BPM)",
    sectionKeymap: "PC Keyboard",
    addNoteMapLabel: "Add a new note to the mapping",
    addNoteMapBtn: "Add",
    sectionShortcuts: "Keyboard shortcuts",
    sectionEQ: "Equalizer",
    eqLow: "Low",
    eqMid: "Mid",
    eqHigh: "High",
    dropNotMidi: "That file isn't a MIDI (.mid/.midi)",
    eqPresetLabel: "Preset",
    eqFlat: "Flat",
    eqRock: "Rock",
    eqClassical: "Classical",
    eqJazz: "Jazz",
    eqPop: "Pop",
    eqElectronic: "Electronic",
    eqVocal: "Piano boost",
    pressKeyToast: "Press the physical key you want to assign…",
    shortcutPlayPause: "Play/Pause",
    shortcutMute: "Mute",
    shortcutSeekBack: "Seek back 5s",
    shortcutSeekFwd: "Seek forward 5s",
    shortcutFullscreen: "Fullscreen",
    shortcutSustain: "Toggle sustain pedal",
    shortcutOpenFile: "Open MIDI file",
    shortcutVolUp: "Volume up",
    shortcutVolDown: "Volume down",
    shortcutObsClean: "Toggle clean mode (OBS)",
    shortcutPlaylistPrev: "Previous track",
    shortcutPlaylistNext: "Next track",
    shortcutStop: "Stop",
    shortcutLoopToggle: "Toggle loop",
    shortcutPlaylistToggle: "Open/close playlist",
    shortcutRecordToggle: "Start/stop video recording",
    groupExport: "Export video",
    sectionExport: "Record and export video",
    keymapHint: 'Click "Remap", then press the physical key you want to use for that note.',
    remap: "Remap",
    resetDefault: "Reset to default",
    ctrlLoad: "Load MIDI button",
    ctrlPlay: "Play button",
    ctrlMidiIn: "MIDI device selector",
    ctrlTempo: "Speed control",
    flagFallingNotes: "Falling notes",
    flagFallingNotesDesc: "Ribbons that fall toward the key.",
    flagSheet: "Sheet music",
    flagSheetDesc: "Staff synced with diatonic position.",
    flagFollow: "Follow mode",
    flagFollowDesc: "Waits for you to play the right note.",
    flagAccuracy: "Accuracy meter",
    flagAccuracyDesc: "Shows live hit percentage.",
    flagObs: "Clean mode (OBS)",
    flagObsDesc: "Hides all UI except the ⚙ icon.",
    hintLoadFile: "Load a MIDI file to begin",
    errorReadingMidi: "Error reading the MIDI file: ",
    webMidiUnavailable: "Web MIDI not available — use clicks or your PC keyboard.",
    webMidiDenied: "MIDI access was denied. Check your browser permissions.",
    accuracyLabel: "Accuracy",
    sampleLoaded: "Audio sample loaded: ",
    sampleDecodeError: "Could not decode the audio file.",
    ctrlTransport: "Rewind/stop/forward buttons",
    ctrlVolume: "Volume control",
    ctrlFullscreen: "Fullscreen button",
    ctrlLoop: "Loop button",
    flagNoteNames: "Note names on keys",
    flagNoteNamesDesc: "Shows the name above each piano key.",
    flagProgress: "Progress bar",
    flagProgressDesc: "Shows song progress and time remaining.",
    flagAutoHide: "Hide mouse while playing",
    flagAutoHideDesc: "Hides the cursor after a few seconds of no movement.",
    flagVirtualClick: "Click on virtual keyboard",
    flagVirtualClickDesc: "Lets you play notes by clicking the on-screen piano.",
    flagSustain: "Hold notes (pedal)",
    flagSustainDesc: "Keeps a note ringing after releasing the key, like a sustain pedal.",
    flagTouchMode: "Touch mode",
    flagTouchModeDesc: "Optimizes the keyboard for touchscreens (auto-detected).",
    chordLabel: "Chord",
    noChord: "",
    sectionNoteNaming: "Note naming system",
    noteNamingEn: "English (C D E)",
    noteNamingLatin: "Latin (Do Re Mi)",
    noteNamingDe: "German (C D E, H)",
    sectionVolume: "Volume",
    fullscreenOn: "Fullscreen",
    shortcutsHint: "Shortcuts: Space play/pause · ← / → seek 5s · M mute · Shift hold for sustain pedal",
    flagLoop: "Loop song",
    flagLoopDesc: "Restarts automatically when it ends.",
    flagBeatLines: "Beat lines",
    flagBeatLinesDesc: "Marks each beat in the falling notes area.",
    flagKeyFx: "Visual key-press effects",
    flagKeyFxDesc: "An expanding flash when you press a key.",
    sectionColorTheme: "Color theme",
    themeBrass: "Brass (default)",
    themeOcean: "Ocean",
    themeRose: "Rose",
    themeEmerald: "Emerald",
    themeMono: "Monochrome",
    themeCustom: "Custom (from image)",
    sectionInstruments: "Instruments per track",
    instrumentsHint: "Appears once a MIDI is loaded. \"Auto-play\" makes that track sound on its own during playback, using the chosen instrument — in Practice you choose which track plays itself vs which you play; in Watch every track always plays itself.",
    trackLabel: "Track",
    trackNoNotes: "no notes",
    trackMute: "Mute",
    trackAuto: "Auto-play",
    trackVisible: "Show in staff/falling notes",
    trackDisable: "Disable track",
    noTracksYet: "Load a MIDI file to see its tracks.",
    watchModeAutoNote: "In Watch mode every track always auto-plays — this switch only applies in Practice mode.",
    modeFree: "Free",
    modeWatch: "Watch",
    modePractice: "Practice",
    freeModeLabel: "Free mode",
    modePromptTitle: "How do you want to use this MIDI?",
    sectionEffects: "Global effects",
    humanizeLabel: "Humanize",
    swingLabel: "Swing",
    flagNoteNamesTiles: "Note names on tiles",
    flagNoteNamesTilesDesc: "Shows the note name on each falling tile.",
    flagPerspective3D: "3D perspective",
    flagPerspective3DDesc: "Visual depth on falling notes (no WebGL).",
    flagBpmPulse: "BPM visual pulse",
    flagBpmPulseDesc: "Highlights the current beat with a light pulse.",
    flagDynamicCamera: "Dynamic camera",
    flagDynamicCameraDesc: "Auto zoom and pan based on note density.",
    flagShowChordNames: "Show chord names",
    flagShowChordNamesDesc: "Displays the chord formed by played notes.",
    sectionLevels: "Difficulty level",
    levelBeginner: "Beginner",
    levelIntermediate: "Intermediate",
    levelAdvanced: "Advanced",
    levelHint: "Adjusts key range, speed and lookahead to the chosen level.",
    perspectiveDepthLabel: "3D depth",
    pulseIntensityLabel: "Pulse intensity",
    cameraSmoothingLabel: "Camera smoothing"
  }
};

export function noteLabelName(note, naming = 'en') {
  const noteNumber = Number(note);
  const names = {
    en: ['C', 'C#', 'D', 'D#', 'E', 'F', 'F#', 'G', 'G#', 'A', 'A#', 'B'],
    latin: ['Do', 'Do#', 'Re', 'Re#', 'Mi', 'Fa', 'Fa#', 'Sol', 'Sol#', 'La', 'La#', 'Si'],
    de: ['C', 'C#', 'D', 'D#', 'E', 'F', 'F#', 'G', 'G#', 'A', 'A#', 'H']
  };

  const list = names[naming] || names.en;
  const octave = Math.floor(noteNumber / 12) - 1;
  return `${list[noteNumber % 12]}${octave}`;
}

export function t(key) {
  const lang = CFG?.language || 'en';
  return (TEXT[lang] && TEXT[lang][key]) || key;
}

export function applyI18n() {
  document.querySelectorAll('[data-i18n]').forEach(el => {
    el.textContent = t(el.dataset.i18n);
  });
  document.querySelectorAll('[data-i18n-label]').forEach(el => {
    el.label = t(el.dataset.i18nLabel);
  });
  document.title = 'Piano';
  // Actualizar etiquetas que dependen de i18n
  if (window.updatePlayButtonLabel) window.updatePlayButtonLabel();
  if (window.updateAccuracyBadge) window.updateAccuracyBadge();
}